#pragma once

enum cancel_state{PTHREAD_CANCEL_DEFERRED,PTHREAD_CANCEL_ASYNCHRONOUS};
enum cancel_type{PTHREAD_CANCEL_ENABLE,PTHREAD_CANCEL_DISABLE};
enum join_state{PTHREAD_JOINABLE, PTHREAD_DETACHED};

#define PTHREAD_CANCELED 8